name: Update changelog
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Needs to match, exactly, the name of a milestone. The version to be released please respect: major.minor.patch or major.minor.patch-beta<number> format. example: 7.4.3 or 7.4.3-beta1'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Run update changelog (manually invoked)        
        uses: grafana/grafana-github-actions-go/update-changelog@main
        with:
          token: ${{ secrets.GRAFANABOT_PAT }}
          version: ${{ inputs.version }}
          metrics_api_key: ${{ secrets.GRAFANA_MISC_STATS_API_KEY }}
          forum_key: ${{ secrets.GRAFANABOT_FORUM_KEY }}
